include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_type_to_string
    - comment_references
    - diagnostic_describe_all_properties
    - empty_statements
    - hash_and_equals
    - invariant_booleans